export default {
  AUTH_LOADING: 'AUTH_LOADING',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_RESTORE: 'AUTH_RESTORE',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
}
